/**
 * File generated by Magnet rest2mobile 1.1 - May 15, 2015 10:47:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.imagesearch.api.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "resultCount" : "174,000",
  "pages" : [ {
    "start" : "0",
    "label" : 1
  }, {
    "start" : "4",
    "label" : 2
  }, {
    "start" : "8",
    "label" : 3
  }, {
    "start" : "12",
    "label" : 4
  }, {
    "start" : "16",
    "label" : 5
  }, {
    "start" : "20",
    "label" : 6
   ...

 */

public class Cursor {

  
  private Integer currentPageIndex;

  
  private String estimatedResultCount;

  
  private String moreResultsUrl;

  
  private List<Page> pages;

  
  private String resultCount;

  
  private String searchResultTime;

  public Integer getCurrentPageIndex() {
    return currentPageIndex;
  }
  public String getEstimatedResultCount() {
    return estimatedResultCount;
  }
  public String getMoreResultsUrl() {
    return moreResultsUrl;
  }
  public List<Page> getPages() {
    return pages;
  }
  public String getResultCount() {
    return resultCount;
  }
  public String getSearchResultTime() {
    return searchResultTime;
  }

  /**
  * Builder for Cursor
  **/
  public static class CursorBuilder {
    private Cursor toBuild = new Cursor();

    public CursorBuilder() {
    }

    public Cursor build() {
      return toBuild;
    }

    public CursorBuilder currentPageIndex(Integer value) {
      toBuild.currentPageIndex = value;
      return this;
    }
    public CursorBuilder estimatedResultCount(String value) {
      toBuild.estimatedResultCount = value;
      return this;
    }
    public CursorBuilder moreResultsUrl(String value) {
      toBuild.moreResultsUrl = value;
      return this;
    }
    public CursorBuilder pages(List<Page> value) {
      toBuild.pages = value;
      return this;
    }
    public CursorBuilder resultCount(String value) {
      toBuild.resultCount = value;
      return this;
    }
    public CursorBuilder searchResultTime(String value) {
      toBuild.searchResultTime = value;
      return this;
    }
  }
}
