/**
 * File generated by Magnet rest2mobile 1.1 - May 15, 2015 10:47:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.imagesearch.api.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.jim.imagesearch.api.controller.api.GoogleImageSearchApi;
import com.jim.imagesearch.api.controller.api.GoogleImageSearchApiFactory;
import com.jim.imagesearch.api.model.beans.*;

/**
* This is generated stub to test {@link GoogleImageSearchApi}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class GoogleImageSearchApiTest extends InstrumentationTestCase {
  private GoogleImageSearchApi googleImageSearchApi;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    GoogleImageSearchApiFactory controllerFactory = new GoogleImageSearchApiFactory(magnetClient);
    googleImageSearchApi = controllerFactory.obtainInstance();

    assertNotNull(googleImageSearchApi);
  }

  /**
    * Generated unit test for {@link GoogleImageSearchApi#searchImage}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testSearchImage() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String q = null;
    String v = null;
    String as_filetype = null;
    String as_sitesearch = null;

    Call<SearchImageResult> callObject = googleImageSearchApi.searchImage(
      q, 
      v, 
      as_filetype, 
      as_sitesearch, null);
    assertNotNull(callObject);

    SearchImageResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
