/**
 * File generated by Magnet rest2mobile 1.1 - May 15, 2015 10:47:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.imagesearch.model;


/**
 * Generated from json example
{
  "start" : "0",
  "label" : 1
}

 */

public class Page {

  
  private Integer label;

  
  private String start;

  public Integer getLabel() {
    return label;
  }
  public String getStart() {
    return start;
  }

  /**
  * Builder for Page
  **/
  public static class PageBuilder {
    private Page toBuild = new Page();

    public PageBuilder() {
    }

    public Page build() {
      return toBuild;
    }

    public PageBuilder label(Integer value) {
      toBuild.label = value;
      return this;
    }
    public PageBuilder start(String value) {
      toBuild.start = value;
      return this;
    }
  }
}
