/**
 * File generated by Magnet rest2mobile 1.1 - May 15, 2015 10:47:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.imagesearch.model;

import java.util.List;

/**
 * Generated from json example
{
  "results" : [ {
    "GsearchResultClass" : "GimageSearch",
    "width" : "639",
    "height" : "425",
    "imageId" : "ANd9GcRSE0jH0QnlnpPfCikEteQX9dOkIx-CEIQ89vOWhP_Jzl-OLT22ZBRXZKU",
    "tbWidth" : "137",
    "tbHeight" : "91",
    "unescapedUrl" : "http://i272.photobucket.com/albums/jj178/MissConstrue_2008/Dog-Head-Pat-2.jpg",
    "url" : "http://i272.photobucket.com/albums/jj178/MissConstrue_2008/Dog-Head-Pat-2.jpg",
    "visibleUrl" : "photobucket.com",
    "title" : "Pat<b>Dog</b>Pictures,Images&amp;Photos|Photobucket",
    "titleNoFormatting" : "PatDogPictures,Images&amp;Photos|Photobucket",
    "originalContextUrl" : "http://photobucket.com/images/pat%20dog",
    "content" : "Pat<b>Dog</b>Pictures,Images",
    "contentNoFormatting" : "PatDogPictures,Images",
    "tbUrl" : "http://t0.gstatic.com/images?q=tbn:ANd9GcRSE0jH0QnlnpPfCikEteQX9dOkIx-CEIQ89vOWhP_Jzl-OLT22ZBRXZKU"
  }, {
    "GsearchResultClass" : "GimageSearch",
    "width" : "640",
      ...

 */

public class ResponseData {

  
  private Cursor cursor;

  
  private List<ImageResult> results;

  public Cursor getCursor() {
    return cursor;
  }
  public List<ImageResult> getResults() {
    return results;
  }

  /**
  * Builder for ResponseData
  **/
  public static class ResponseDataBuilder {
    private ResponseData toBuild = new ResponseData();

    public ResponseDataBuilder() {
    }

    public ResponseData build() {
      return toBuild;
    }

    public ResponseDataBuilder cursor(Cursor value) {
      toBuild.cursor = value;
      return this;
    }
    public ResponseDataBuilder results(List<ImageResult> value) {
      toBuild.results = value;
      return this;
    }
  }
}
