/**
 * File generated by Magnet rest2mobile 1.1 - May 15, 2015 10:47:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.imagesearch.model;


/**
 * Generated from json example
{
  "responseData" : {
    "results" : [ {
      "GsearchResultClass" : "GimageSearch",
      "width" : "639",
      "height" : "425",
      "imageId" : "ANd9GcRSE0jH0QnlnpPfCikEteQX9dOkIx-CEIQ89vOWhP_Jzl-OLT22ZBRXZKU",
      "tbWidth" : "137",
      "tbHeight" : "91",
      "unescapedUrl" : "http://i272.photobucket.com/albums/jj178/MissConstrue_2008/Dog-Head-Pat-2.jpg",
      "url" : "http://i272.photobucket.com/albums/jj178/MissConstrue_2008/Dog-Head-Pat-2.jpg",
      "visibleUrl" : "photobucket.com",
      "title" : "Pat<b>Dog</b>Pictures,Images&amp;Photos|Photobucket",
      "titleNoFormatting" : "PatDogPictures,Images&amp;Photos|Photobucket",
      "originalContextUrl" : "http://photobucket.com/images/pat%20dog",
      "content" : "Pat<b>Dog</b>Pictures,Images",
      "contentNoFormatting" : "PatDogPictures,Images",
      "tbUrl" : "http://t0.gstatic.com/images?q=tbn:ANd9GcRSE0jH0QnlnpPfCikEteQX9dOkIx-CEIQ89vOWhP_Jzl-OLT22ZBRXZKU"
    }, {
      "GsearchResultClass" : "GimageSearch",
        ...

 */

public class SearchImageResult {

  
  private ResponseData responseData;

  
  private Integer responseStatus;

  public ResponseData getResponseData() {
    return responseData;
  }
  public Integer getResponseStatus() {
    return responseStatus;
  }

  /**
  * Builder for SearchImageResult
  **/
  public static class SearchImageResultBuilder {
    private SearchImageResult toBuild = new SearchImageResult();

    public SearchImageResultBuilder() {
    }

    public SearchImageResult build() {
      return toBuild;
    }

    public SearchImageResultBuilder responseData(ResponseData value) {
      toBuild.responseData = value;
      return this;
    }
    public SearchImageResultBuilder responseStatus(Integer value) {
      toBuild.responseStatus = value;
      return this;
    }
  }
}
