/**
 * File generated by Magnet rest2mobile 1.1 - May 15, 2015 10:47:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.imagesearch.api.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.jim.imagesearch.api.model.beans.*;

public interface GoogleImageSearchApi {

  /**
   * Generated from URL GET https://ajax.googleapis.com/ajax/services/search/images?q=dog&v=1.0&as_filetype=jpg&as_sitesearch=photobucket.com
   * GET ajax/services/search/images
   * @param q  style:QUERY
   * @param v  style:QUERY
   * @param as_filetype  style:QUERY
   * @param as_sitesearch  style:QUERY
   * @param listener
   * @return SearchImageResult
   */
  Call<SearchImageResult> searchImage(
     String q,
     String v,
     String as_filetype,
     String as_sitesearch,
     StateChangedListener listener
  );


}
