/**
 * File generated by Magnet rest2mobile 1.1 - May 15, 2015 10:47:42 PM
 * @see {@link http://developer.magnet.com}
 */

package com.jim.imagesearch.api.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.jim.imagesearch.api.model.beans.*;

public class GoogleImageSearchApiFactory extends ControllerFactory<GoogleImageSearchApi> {
  public GoogleImageSearchApiFactory(MagnetMobileClient magnetClient) {
    super(GoogleImageSearchApi.class, GoogleImageSearchApiSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller GoogleImageSearchApi
  public static class GoogleImageSearchApiSchemaFactory extends AbstractControllerSchemaFactory {
    private static GoogleImageSearchApiSchemaFactory __instance;

    public static synchronized GoogleImageSearchApiSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new GoogleImageSearchApiSchemaFactory();
      }

      return __instance;
    }

    private GoogleImageSearchApiSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method searchImage
      JMethod method1 = addMethod("searchImage",
        "ajax/services/search/images",
        "GET",
        SearchImageResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://ajax.googleapis.com");
      method1.addParam("q",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("v",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("as_filetype",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("as_sitesearch",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
